//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmrEmeci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> FechaAcceso { get; set; }
        public string NoTarjeta { get; set; }
    }
}
